%% BUILD_ACCEL_SIMULINK  Generate accel_sim.slx from the validated accel physics.
% Programmatically constructs a Simulink model of the inertia-based accel
% event (same equations as accel_model.m):
%   dw/dt = [T_M(w)*eta - n*r*(b*w^2 + C) - T_F] / I_den,   v = r*n*w,  x = INT v
% Structure: a MATLAB Function block computes the derivative (incl. the
% traction-limit / weight-transfer fixed-point solve); two Integrators carry
% the states w (motor speed) and x (distance); a Stop block ends at 75 m.
%
% REQUIRES SIMULINK. Run:  >> build_accel_simulink   then   >> sweep_accel_sim
% Constants are pulled from params_cfr26.m at build time (single source of
% truth); re-run this builder after changing params.
% VALIDATED: 0-75m at 4.61:1 = 4.80 s, matching accel_model.m (4.80 s) at the
% current eta_drivetrain = 0.794 (rebuild after changing params to stay in sync).

function build_accel_simulink()
addpath(fullfile(fileparts(mfilename('fullpath')), 'lib'));  % works wherever MATLAB is pointed
p = params_cfr26();
mdl = 'accel_sim';
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);

% ---- Derivative code (constants injected from params) ----
arr = @(v) ['[' sprintf('%g ', v) ']'];
script = sprintf([ ...
'function [domega_dt, v] = dyn(omega, G)\n' ...
'%%#codegen\n' ...
'r=%g; eta=%g; m=%g; rho=%g; CdA=%g; ClA=%g; Crr=%g;\n' ...
'rs=%g; ra=%g; hcg=%g; L=%g; g=%g; redline=%g; Tcap=%g; TF=%g;\n' ...
'Irot=%g; Idl=%g; Iwh=%g; nw=%g;\n' ...
'Prpm=%s; Pkw=%s;\n' ...
'PDX1=%g; PDX2=%g; FNOM=%g; LMUX=%g;\n' ...
'n = 1/G;\n' ...
'Iden = Irot + Idl + nw*Iwh*n^2 + m*n^2*r^2;\n' ...
'b = 0.5*rho*r^2*n^2*(CdA + Crr*ClA);\n' ...
'Cc = m*g*Crr;\n' ...
'v = r*n*omega;\n' ...
'rpm = omega*60/(2*pi);\n' ...
'if rpm < 50\n' ...
'    Tm = Tcap;\n' ...
'else\n' ...
'    Pk = interp1(Prpm, Pkw, min(rpm,redline), ''linear'', ''extrap'');\n' ...
'    Tm = min(Tcap, Pk*9549/rpm);\n' ...
'end\n' ...
'Tm = Tm*eta;\n' ...
'Fdown = 0.5*rho*ClA*v^2;\n' ...
'a = 0; domega_dt = 0;\n' ...
'for it = 1:3\n' ...
'    Fzr = m*g*rs + m*a*hcg/L + Fdown*ra;\n' ...
'    dfz = (Fzr/2 - FNOM)/FNOM;\n' ...
'    mu = max(LMUX*(PDX1 + PDX2*dfz), 0.5);\n' ...
'    Tuse = min(Tm, mu*Fzr*r*n/eta);\n' ...
'    domega_dt = (Tuse - n*r*(b*omega^2 + Cc) - TF)/Iden;\n' ...
'    a = r*n*domega_dt;\n' ...
'end\n'], ...
p.r_wheel, p.eta_drivetrain, p.m_car, p.rho_air, p.CdA, p.ClA, p.Crr, ...
p.rear_static, p.rear_aero, p.h_cg, p.L_wb, p.g, p.redline, p.T_flat_cap, p.T_F, ...
p.I_rotor, p.I_driveline, p.I_wheel, p.n_wheels, arr(p.Prpm), arr(p.Pkw), ...
p.tir.PDX1, p.tir.PDX2, p.tir.FNOMIN, p.tir.LMUX);

% ---- Blocks ----
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/dyn'], 'Position',[300 100 400 180]);
root = sfroot;
ch = root.find('-isa','Stateflow.EMChart','-and','Path',[mdl '/dyn']);
ch.Script = script;

add_block('simulink/Continuous/Integrator', [mdl '/omega'], 'InitialCondition','0', 'Position',[470 110 510 150]);
add_block('simulink/Continuous/Integrator', [mdl '/dist'],  'InitialCondition','0', 'Position',[470 180 510 220]);
add_block('simulink/Sources/Constant', [mdl '/Gval'], 'Value','G_ratio', 'Position',[180 150 260 180]);
add_block('simulink/Logic and Bit Operations/Compare To Constant', [mdl '/reach75'], ...
    'relop','>=', 'const','75', 'Position',[560 185 620 215]);
add_block('simulink/Sinks/Stop Simulation', [mdl '/Stop'], 'Position',[660 185 690 215]);
add_block('simulink/Sinks/To Workspace', [mdl '/w_out'], 'VariableName','w_log','SaveFormat','Timeseries','Position',[560 110 620 140]);
add_block('simulink/Sinks/To Workspace', [mdl '/x_out'], 'VariableName','x_log','SaveFormat','Timeseries','Position',[560 245 620 275]);
% Scope so you can WATCH distance + speed build during a Run (double-click it to open).
add_block('simulink/Sinks/Scope', [mdl '/Scope'], 'NumInputPorts','2', 'Position',[680 300 720 350]);
% A "button": an empty (port-less) subsystem whose double-click runs the whole sweep,
% so nobody has to type anything. Green so it stands out.
add_block('built-in/Subsystem', [mdl '/RUN SWEEP (double-click)'], 'Position',[150 300 340 350]);
set_param([mdl '/RUN SWEEP (double-click)'], 'OpenFcn','sweep_accel_sim', 'BackgroundColor','green');

% ---- Wiring ----
add_line(mdl,'Gval/1','dyn/2','autorouting','on');
add_line(mdl,'dyn/1','omega/1','autorouting','on');
add_line(mdl,'omega/1','dyn/1','autorouting','on');   % state feedback
add_line(mdl,'omega/1','w_out/1','autorouting','on');
add_line(mdl,'dyn/2','dist/1','autorouting','on');
add_line(mdl,'dist/1','reach75/1','autorouting','on');
add_line(mdl,'dist/1','x_out/1','autorouting','on');
add_line(mdl,'reach75/1','Stop/1','autorouting','on');
add_line(mdl,'dist/1','Scope/1','autorouting','on');   % distance -> scope
add_line(mdl,'dyn/2','Scope/2','autorouting','on');    % speed -> scope

% ---- Solver / config ----
set_param(mdl,'SolverType','Variable-step','Solver','ode45','StopTime','15','MaxStep','0.005');
% Make the model runnable standalone. The Gval Constant block reads 'G_ratio' from
% the base workspace; if someone just opens accel_sim.slx and hits Run without
% setting it, the block errors ("Invalid setting ... for parameter 'Value'"). This
% InitFcn defaults it to the current 4.61 only when it isn't already defined, so a
% bare Run works AND sweep_accel_sim (which sets G_ratio each iteration) still wins.
set_param(mdl,'InitFcn','if ~exist(''G_ratio'',''var''), G_ratio = 4.61; end');
assignin('base','G_ratio',4.61);

% When the model opens, put the repo + lib on the MATLAB path so a teammate can just
% open accel_sim.slx and use it (the RUN SWEEP button, params, etc.) WITHOUT running
% START.m first. Uses the .slx's own folder, so it works wherever the repo lives.
set_param(mdl,'PostLoadFcn', ...
    'p=fileparts(get_param(''accel_sim'',''FileName'')); if ~isempty(p), addpath(p, fullfile(p,''lib'')); end');

% Print a RESULT when you hit Run, so a bare Run isn't silent. The Stop block ends
% the sim exactly at 75 m, so the final SimulationTime IS the 0-75 m time -- read it
% straight off, no dependence on how the run logs to the workspace. The Scope shows
% the distance/speed curves. Stays quiet during sweep_accel_sim (sets SWEEP_MODE).
stopfcn = [ ...
 'if ~exist(''SWEEP_MODE'',''var''),' ...
 '  fprintf(''\naccel_sim: 0-75 m at %.2f:1 = %.2f s   (double-click the Scope for the curves)\n'',' ...
 '          G_ratio, get_param(''accel_sim'',''SimulationTime''));' ...
 'end'];
set_param(mdl,'StopFcn',stopfcn);

% Save the Scope in an open state so it pops up on Run without the user hunting for it.
try, open_system([mdl '/Scope']); catch, end

% On-canvas instructions so the model explains itself.
try
    a = Simulink.Annotation(mdl, sprintf([ ...
        'HOW TO USE\n' ...
        '  - Hit  Run  (top toolbar) for ONE ratio  (G_ratio, default 4.61).\n' ...
        '    -> prints the 0-75 m time + pops a distance/rpm plot.\n' ...
        '  - Double-click the green  RUN SWEEP  block for ALL ratios\n' ...
        '    -> table + a 0-75 m vs gear-ratio plot.  No typing needed.']));
    a.position = [150 380 620 470];
    a.FontSize = 11;
catch
end

save_system(mdl, fullfile(pwd, [mdl '.slx']));
fprintf('Built %s.slx.\n', mdl);
fprintf('  Open it and hit Run for one ratio, or double-click RUN SWEEP for all ratios.\n');
fprintf('  Command line:  sweep_accel_sim   (same sweep + plot)\n');
end
