#!/usr/bin/env python3
"""Builds docs/GEAR_RATIO_MEETING_2026.md from the regenerated sim outputs."""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(p):
    with open(os.path.join(ROOT, p)) as f:
        return list(csv.DictReader(f))


M = {int(r["driven_teeth"]): r for r in load("output/gear_meeting_matrix.csv")}
P = {int(r["driven_teeth"]): r for r in load("output/gear_points_model.csv")}

L = []
w = L.append
w("# Gear ratio freeze -- meeting pack")
w("")
w("Everything here was regenerated today by running the whole MATLAB suite end to end.")
w("Reproduce with `START`, then `gear_ratio_optimization`, `accel_model`, `gear_meeting_matrix`,")
w("then `python tools/gear_points_model.py`. The regression suite `verify_math` passes clean.")
w("")
w("## 0. Read this first")
w("")
w("**Concordia 2026: 476.1 points, 19th place. Endurance scored 25.0 out of 275.**")
w("")
w("That number should frame the whole meeting. The gear ratio moves about **6 points** across")
w("the entire 4.2 to 4.8 band. Finishing endurance is worth **250**. The ratio decision is")
w("roughly **40x less important than not DNF-ing**, so the question is not which ratio scores")
w("best, it is which ratio is least likely to stop the car.")
w("")
w("## 1. The table")
w("")
w("Driver fixed at 13T (splined bought part). Driven sprocket is the only knob. 0-75 m is at")
w("the car's real 123 Nm request with TC active, on the grip we measured (mu 0.853), not the")
w("150 Nm datasheet map on clean belt grip.")
w("")
w("| Driven | Ratio | 0-75 m (s) | Accel pts | Wh/lap | Effic pts | Accel+Eff | vs 30T | "
  "Final SOC | Top spd | Exits past knee |")
w("|---|---|---|---|---|---|---|---|---|---|---|")
for n in range(26, 35):
    m, p = M[n], P[n]
    band = " **<- band**" if 4.2 <= float(m["ratio"]) <= 4.8 else ""
    cur = " **(CURRENT)**" if n == 30 else ""
    w("| %d T%s | %.4f%s | %.4f | %.1f | %.1f | %.1f | %.1f | %+.1f | %.3f%% | %.1f | %.1f%% |"
      % (n, cur, float(m["ratio"]), band, float(p["t75_s_mu853"]), float(p["accel_pts"]),
         float(p["wh_per_lap"]), float(p["efficiency_pts"]), float(p["accel_plus_eff"]),
         float(p["vs_30T"]), float(m["SOC98"]), float(m["top_speed_kph"]),
         float(m["exits_past_knee_pct"])))
w("")
w("## 2. What the points actually say")
w("")
w("Inside 4.2 to 4.8 the spread is **6.3 points**, and it is almost entirely accel:")
w("")
w("| | 28T (4.31) | 30T (4.62) | 31T (4.77) |")
w("|---|---|---|---|")
w("| Accel pts | %.1f | %.1f | **%.1f** |" % tuple(float(P[k]["accel_pts"]) for k in (28, 30, 31)))
w("| Efficiency pts | **%.1f** | %.1f | %.1f |" % tuple(float(P[k]["efficiency_pts"]) for k in (28, 30, 31)))
w("| Total modelled | %.1f | %.1f | **%.1f** |" % tuple(float(P[k]["accel_plus_eff"]) for k in (28, 30, 31)))
w("| vs current | %+.1f | 0 | **%+.1f** |" % (float(P[28]["vs_30T"]), float(P[31]["vs_30T"])))
w("")
w("**The efficiency gain from gearing longer does not pay for the accel loss.** Going 30T to 28T")
w("costs 5.2 accel points and buys back 0.2 efficiency points. That is a bad trade, and it")
w("corrects the older brief in `GEAR_RATIO_DECISION.md`, which assumed efficiency would roughly")
w("compensate. At these magnitudes it does not. The accel scoring curve is steep, about")
w("**49.9 points per second** at our operating point, and the efficiency curve is nearly flat,")
w("1.2% of energy across the whole 26T to 34T sweep.")
w("")
w("Calibration, so anyone can check it:")
w("")
w("- Our 2026 accel score of 47.8 inverts through the rules formula to Tyour/Tmin = 1.2228.")
w("  With our sim time of 4.6975 s that puts the field best at **3.842 s**. Wisconsin scored")
w("  100.0, so they set it.")
w("- Field best energy is **83.7 Wh/lap** (Missouri S&T, 2025 e-meter, n=28 teams). We sit at")
w("  about **240 Wh/lap**, near the bottom of the field, which matches our 38.0 efficiency score.")
w("")
w("## 3. What is NOT in that table, and it is most of the points")
w("")
w("| Event | Points | Modelled? |")
w("|---|---|---|")
w("| Acceleration | 100 | yes |")
w("| Efficiency | 100 | yes |")
w("| Skidpad | 75 | ratio-independent |")
w("| **Autocross** | **125** | **NO** |")
w("| **Endurance time** | **250** | **NO** |")
w("")
w("**There is no lap-time-vs-ratio model in this repo.** Building one to fill in 375 points")
w("would have been the most misleading thing this study could do, so it is left out. The table")
w("in section 1 is a **floor** on what the ratio is worth, not the whole answer.")
w("")
w("The one driveability proxy we do have is **exits past the torque knee**: %.1f%% at 28T, "
  "%.1f%% at 30T, %.1f%% at 31T."
  % tuple(float(M[k]["exits_past_knee_pct"]) for k in (28, 30, 31)))
w("Gearing shorter puts more corner exits on the falling part of the torque curve, which is the")
w("classic driver complaint. That works **against** 31T in exactly the 125 autocross points the")
w("table cannot score. Nobody should pretend to know how big that effect is, but it is the reason")
w("not to simply take the highest number in section 2.")
w("")
w("## 4. Grip sensitivity, the reason not to go past 31T")
w("")
w("| Driven | Ratio | t75 clean belt | t75 our measured grip | penalty |")
w("|---|---|---|---|---|")
for n in range(26, 35):
    m = M[n]
    w("| %dT | %.4f | %.4f | %.4f | %+.4f |"
      % (n, float(m["ratio"]), float(m["t75_mu100"]), float(m["t75_mu853"]),
         float(m["grip_penalty_s"])))
w("")
w("Long ratios barely notice the grip assumption. Short ones do. Past 32T the car starts")
w("spinning and TC eats the gain, which is why 32T is the peak on measured grip while 33T is the")
w("peak on clean belt. Our grip number is borrowed off a different tyre and is the input we trust")
w("least, so **anything past about 31T bets the accel case on the weakest data we have.**")
w("")
w("## 5. Recommendation")
w("")
w("**Stay at 30T. Treat 31T as the only upgrade worth arguing for.**")
w("")
w("- **30T (4.6154)** is already fitted. No new part, no chain change, no axle move. Zero risk.")
w("- **31T (4.7692)** is +1.3 modelled points and the axle moves **0.14 mm**, which is nothing.")
w("  But it needs an offset link (odd tooth count) and it pushes exits-past-knee from 37% to 41%.")
w("  So it is +1.3 points you can measure against a driveability cost you cannot, plus a weaker")
w("  chain joint. **Not obviously worth it.**")
w("- **28T (4.3077)** costs 5.0 points and buys 0.4 points of SOC margin. Only defensible if the")
w("  team decides endurance is energy limited, and nobody has shown that it is.")
w("")
w("**The real decision in the room is not the ratio.** It is: *why did we score 25 on endurance?*")
w("If it was energy, 28T becomes the answer and 5 points is cheap insurance. If it was mechanical")
w("or thermal, the ratio is irrelevant and 30T stays. **Settle that first, then pick the ratio.**")
w("")
w("## 6. Mechanical constraints, all settled")
w("")
w("From the CAD, full detail in `sprocket_configs.md`:")
w("")
w("- Driver 13T sits on a **6-lobe spline, 21.0 / 25.0 / 5.0 mm**, on shaft DT-P2127. Bought part,")
w("  so any driver change needs that exact bore.")
w("- Driven sprocket is **made in house**, bore 45.60, **6 x 6.31 holes on a 92.69 BCD**. Every")
w("  tooth count in the sweep reuses that same mounting.")
w("- Centre distance **152.08 mm** measured. Chain is 520, pitch 15.875, plate half height 7.2517.")
w("- Chassis envelope quoted as **156.3 to 171.4 mm diameter** for 28T to 31T, chain included.")
w("  **32T would need 176.5 mm and is not covered by what chassis has been given.**")
w("- Wrap angle passes everywhere. Worst case 34T is 139.3 deg against a 120 deg limit.")
w("- Axle move from today's 152.08 to land on an even chain: 28T -2.09 mm, 30T +4.76 mm,")
w("  31T -0.14 mm. All small.")
w("")
w("## 7. Corrections made today")
w("")
w("- `gear_decision_summary.m` had **`pitch = 12.7`** for a 520 chain. That is #40 half-inch, not")
w("  520. It is why the old brief quoted a 242 mm centre distance. Fixed to 15.875 mm and 42")
w("  links, which now agrees with both the 152.08 mm CAD measurement and the independent Mott")
w("  calculation.")
w("- The sweeps in `params_cfr26.m` and `accel_model.m` now include the **buildable** sprocket")
w("  ratios, so every number above is evaluated exactly on a ratio you can bolt on. Previously")
w("  they were interpolated between grid points. Nothing was removed from either sweep list.")
w("- The old brief's claim that efficiency roughly compensates for lost accel does not survive")
w("  the points arithmetic. See section 2.")
w("")
w("## 8. Where the numbers live")
w("")
w("| File | What |")
w("|---|---|")
w("| `output/gear_meeting_matrix.csv` | every ratio axis at the buildable ratios, both grip cases |")
w("| `output/gear_points_model.csv` | the FSAE points table |")
w("| `output/gear_points_model.txt` | same, with the full calibration trail |")
w("| `output/gear_ratio_results.csv` | endurance SOC and efficiency, 22 ratios |")
w("| `output/accel_results.csv` | accel sweep, 34 ratios |")
w("| `output/emeter_benchmark.csv` | 2025 competition field energy, 28 teams |")
w("| `CFR27_Sprocket_Study.xlsx` | the mechanical side, live PASS/FAIL |")

path = os.path.join(ROOT, "docs", "GEAR_RATIO_MEETING_2026.md")
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print("wrote", path, len(L), "lines")
